name = "maison-du-tresor-forms"
main = "index.js"
compatibility_date = "2023-10-02"

# Configure environment variables
[vars]
RECIPIENT_EMAIL = "maisondutresor26@gmail.com"

# Add your Resend API key in the .dev.vars file locally or in the Cloudflare dashboard
# RESEND_API_KEY = "your-resend-api-key"
